services:
  frontend:
    image: ghcr.io/lordtkay/foosball-frontend:0.0.1
    container_name: foosball-frontend
    ports:
      - "29000:80"
    networks:
      - foosball
  backend:
    image: ghcr.io/lordtkay/foosball-backend:0.0.6
    container_name: foosball-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "29001:8080"
    networks:
      - foosball
    healthcheck:
      test: wget -T5 -qO- http://localhost:8080/api/actuator/health | grep UP || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  database:
    image: mariadb:latest
    container_name: foosball-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foosball
    ports:
      - "29002:3306"
    networks:
      - foosball
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql

networks:
  foosball:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/foosball/mysql
      o: bind